name: Zip WordPress Theme

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP of theme
        run: |
          zip -r theme.zip . -x "*.git*" ".github/*"

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wordpress-theme
          path: theme.zip
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: theme.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

