name: Build & Release WordPress Theme

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP of theme
        run: |
          zip -r theme.zip . -x "*.git*" ".github/*"

      - name: Create tag automatically
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          TAG="v$(date +'%Y%m%d-%H%M%S')"
          echo "TAG=$TAG" >> $GITHUB_ENV
          git tag $TAG
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} $TAG

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: theme.zip
          overwrite_files: true
        env:
          TOKEN: ${{ secrets.TOKEN }}
